### ISSUE TITLE
How much effort do you think it would take to get basic compatibility with GIMP 2.10?

### ISSUE THREAD

**Issue by bibliophilus** [muggenhor/focus-blur#2]
I'm not trying to rush anyone to create a GIMP 2.10 compatible version - people have other things to do, I get that. I just wanted to know about the time and effort estimate about how much work stills needs to be put in before the plugin gets there. Just as far as you can see it right now, it doesn't have to be detailed. 

Admittedly, I might be having the unrealistic hope that a user can try to troubleshoot the plugin's compatibility with their particular PC and OS. In a way, I'm also asking for someone who knew the details to kill that hope quickly so I can move on.

**Comment by muggenhor** [comment]
Just doing such an estimate would cost more time than I'm willing to spend on. Frankly it's something I don't like to do at work so am definitely not going to do here.

Additionally: I'm closing issue tracking for this repository. Because my primary purpose of putting this on GitHub was to give this code, written by someone else, a place to be hosted where it's possible to work on at a later date.
